version: '3'

services:
  load_balancer:
    image: anroe/nginx-geoip2
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./GeoLite2-ASN.mmdb:/etc/nginx/GeoLite2-ASN.mmdb

    networks:
      - mynetwork

  uk:
    image: nginx:1.21.0
    container_name: uk
    ports:
      - "8081:80"
    volumes:
      - ./nginx/uk:/usr/share/nginx/html
    networks:
      - mynetwork

  us1:
    image: nginx:1.21.0
    container_name: us1
    ports:
      - "8082:80"
    volumes:
      - ./nginx/us:/usr/share/nginx/html
    networks:
      - mynetwork

  us2:
    image: nginx:1.21.0
    container_name: us2
    ports:
      - "8083:80"
    volumes:
      - ./nginx/us:/usr/share/nginx/html
    networks:
      - mynetwork

  rest:
    image: nginx:1.21.0
    container_name: rest
    ports:
      - "8084:80"
    volumes:
      - ./nginx/rest:/usr/share/nginx/html
    networks:
      - mynetwork

  backup:
    image: nginx:1.21.0
    container_name: backup
    ports:
      - "8085:80"
    volumes:
      - ./nginx/backup:/usr/share/nginx/html
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
